### ISSUE TITLE
Project Milestones

### ISSUE THREAD

**Issue by accu-clw** [ShipEngine/shipengine-php#4]
Hi :wave:

I've starred your project and am watching with interest. Do you have any estimates on when this is going to get a public release?

We are in the process of upgrading our internal tooling to PHP >=7.4 and I would be keen to revisit this as a possible alternative to our current integration, which is lacking many features.

Thanks!

**Comment by anthonyshull** [comment]
Hi! Sorry this issue just passed right through my inbox. Our current target is end of February to have four key behaviors:

1. Validate an address
2. Track a package
3. Create a shipment
4. Calculate shipment costs

We took a break from releases because we decided to back-track and create an upstream service to encapsulate business logic. Any feedback you have will be much appreciated when we start rolling out releases again.

Thanks!

**Comment by accu-clw** [comment]
> Hi! Sorry this issue just passed right through my inbox. Our current target is end of February to have four key behaviors:
> 
> 1. Validate an address
> 2. Track a package
> 3. Create a shipment
> 4. Calculate shipment costs
> 
> We took a break from releases because we decided to back-track and create an upstream service to encapsulate business logic. Any feedback you have will be much appreciated when we start rolling out releases again.
> 
> Thanks!

No problem, it's been hectic here too! We shall definitely keep an eye on this progression.

The outlined functions cover our most basic needs currently, so hopefully we can test this within the coming weeks.

Thanks for your response @anthonyshull :+1:

**Comment by accu-clw** [comment]
Closing following the above discussion. Thanks all!
